branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
#install:
#  - rakudobrew build-panda
#  - panda installdeps .
script:
  - make test
  - make install PREFIX=/home/travis/.rakudobrew/moar-nom/install/share/perl6/site
  - perl6 -e 'use Native::LibC <puts>; puts "ok."'
