notifications:
  email: false
branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-panda
script:
  - panda install .
  - perl6 -e 'use Native::LibC <puts>; puts "ok."'
  - perl6 -e 'use Native::LibC <errno>; errno(42); say errno'
